### ISSUE TITLE
Guía de estilo

### ISSUE THREAD

**Issue by paocorrales** [AgRoMeteorologiaINTA/agroclimatico#2]
Abro este issue para ponernos de acuerdo en cuanto al estilo de código e idioma usado internamente en las funciones. Luego este issue puede pasar a ser un md como parte del paquete. 

En general proponemos usar la guía de estilo de [Tidyverse](https://style.tidyverse.org/index.html), aquí algunas aclaraciones y detalles.

### Funciones

- Nombres de funciones y sus argumentos
     - snake_case
     - en español (evitando caracteres especiales)
- Variables y estructura interna de funciones
    - En inglés (para que sea consistente con el resto de R)
- Mensajes de error en español

### Documentación

En español

**Comment by yabellini** [comment]
Perfecto.
