### ISSUE TITLE
Propuesta de etiquetas

### ISSUE THREAD

**Issue by yabellini** [AgRoMeteorologiaINTA/agroclimatico#24]
A ver que les parece esta propuesta de etiquetas para poder categorizar los issues:

Tipo: bug, feature, discussion, action
Estado: current, in-progress, ready-to-review
Razón por la que se cerró: finished, wont-fix, duplicate

**Comment by paocorrales** [comment]
En estado deberíamos sumar "closed" o simplemente se saca la etiqueta de estado y se cierra el issue?

**Comment by eliocamp** [comment]
Creo que está bien lo de dejarle la etiqueta con la razón por la que se cerró.

**Comment by eliocamp** [comment]
finished, podría moverse a tag de estado.

**Comment by yabellini** [comment]
Closed sería que se cerró y ya no aparece el issue como abierto.  Así que no lo agregaría como etiqueta.  Sacaría la etiqueda del estado actual y lo cerraría.  La idea del finished capaz que se duplica con la idea de cerrado.  Más que nada las etiquetas quedarías como una razón por la que lo cerramos asociadas a issues cerrados sin resolver.
