### ISSUE TITLE
USO DE LA FUNCIÓN MAPEAR

### ISSUE THREAD

**Issue by NatiGattinoni** [AgRoMeteorologiaINTA/agroclimatico#35]
quería dejar este comentario.
cuando utilicé el ejemplo para la función mapear me apareció este error
![image](https://github.com/AgRoMeteorologiaINTA/agromet/assets/69041826/7764668a-a56b-4bd8-883b-9624706b9ab9)

según lo que busqué en la web, tuve que **Rstart R y corrió todo perfectamente**

En la web decían como es que es un error de la versión de DataSpell con respecto a la de R4.2.3 que es la que yo tengo

**Comment by paocorrales** [comment]
Cierro esto ya que no sería un problema actual. Si vuelve a suceder, por favor reportalo nuevamente!
