### ISSUE TITLE
Considerar cambiar el nombre al paquete

### ISSUE THREAD

**Issue by paocorrales** [AgRoMeteorologiaINTA/agroclimatico#39]
Existe otro paquete [agrometR](https://github.com/adriancorrendo/AgrometR) que accede a los datos de tiempo. Esto es parte de la Red Agroclimática Nacional de Chile que tiene el mismo nombre. El consenso es cambiar el nombre de nuestro paquete y queda definir cual.

Algunas ideas que se mencionaron:
* climagro: el problema es que hay una empresa de software que tiene el mismo nombre y sería confuso
* metagro
* meteoagro
* demeter

**Comment by eliocamp** [comment]
demeter me gustó. Es la diosa griega de la agricultura (otras cosas, porque las deidades Griegas hacían multitasking), tiene "met" de meteorología y la "r" de R.

**Comment by NatiGattinoni** [comment]
Le comenté a Gabriel y él propuso
AgroInta
MeteoInta
es valido poner la institución en el nombre?

**Comment by paocorrales** [comment]
No hay ninguna regla sobre poner o no el nombre de una institución. La única contra que veo es que de la sensación de que el paquete es para uso interno del INTA y creo que estaría bueno ampliar el público que pueda usar el paquete. 

Otra cosa, es más cómodo y menos propenso a errores cuando los nombres no tienen mayúsculas. Habían charlando sobre eso en este caso?

**Comment by yabellini** [comment]
No usaría agro INTA porque es muy genérico, agro es mucho más que meteorología aplicada al agro y el INTA hace muchas más cosas que agrometeorología. Difícil entender que hace el paquete por el nombre.

**Comment by NatiGattinoni** [comment]
al final se hizo viernes y finalizando el periodo de propuesta de nombres:ClimR
ClimavariabR
VariaClimR
ClimVarR

**Comment by paocorrales** [comment]
Creo que habíamos charlado de agroclima pero lo descartamos porque hay una empresa con ese nombre y pensamos que la gente podía pensar que el paquete es de ellos. 

agroclimr es bastante parecido a agroclima pero puede llegar a andar. 

Entre las otras opciones no veo la relación con el agro, suenan a paquetes de climatologia me parece.

**Comment by paocorrales** [comment]
@NatiGattinoni @eliocamp @yabellini si no hay objeciones para mañana a la tarde, cambiamos a agroclimR, les parece?

**Comment by paocorrales** [comment]
Nombre cambiado! Por ahora el link https://github.com/AgRoMeteorologiaINTA/agromet redirige a este repo pero no sirve para instalar el paquete, para eso hay que usar el nuevo nombre. 

Voy a crear un repo agromet con información para instalar el paquete con el nuevo nombre, en caso de que alguien lo intente hacer usando agromet

**Comment by paocorrales** [comment]
Luego de haber hecho todos los cambios a agroclimr, volví al issue de revisión y recordé que hay un paquete agroclim. Con lo cual estamos de vuelta en la misma. Me quedé sin ideas.

**Comment by yabellini** [comment]
Sugiero agroclimatico

**Comment by paocorrales** [comment]
Cambió a agroclimático. Gracias por todos los aportes!
